/* Math Concept Content — 이하이 / 중1 / 일차방정식 / contentVersion 2 */
window.MATH_CONTENT_VERSION="20260831-math-2";
window.MATH_CONTENT={version:2,units:{"linear-equation":{
  id:"linear-equation",grade:"middle1",gradeLabel:"중1",title:"일차방정식",contentVersion:2,
  prerequisites:[
    {id:"signed-number",title:"양수와 음수",description:"양수와 음수의 계산을 확인해요.",question:{id:"m1-linear-v2-pre-01",grade:"middle1",unit:"linear-equation",conceptId:"signed-number",type:"multiple-choice",question:"(-3) + 5의 값은 무엇일까요?",choices:["-8","-2","2","8"],correctAnswer:"2",explanation:"-3에서 5만큼 증가하면 2가 됩니다."},review:{summary:"양수와 음수의 계산에서는 수가 어느 방향으로 변하는지 생각해요.",example:"(-2) + 5 = 3",question:{id:"m1-linear-v2-review-01",grade:"middle1",unit:"linear-equation",conceptId:"signed-number",type:"multiple-choice",question:"(-4) + 7의 값은 무엇일까요?",choices:["-11","-3","3","11"],correctAnswer:"3",explanation:"-4에서 7만큼 증가하면 3입니다."}}},
    {id:"substitution",title:"문자의 사용과 대입",description:"문자에 수를 넣어 식의 값을 구할 수 있는지 확인해요.",question:{id:"m1-linear-v2-pre-02",grade:"middle1",unit:"linear-equation",conceptId:"substitution",type:"multiple-choice",question:"x = 3일 때, 2x + 1의 값은 무엇일까요?",choices:["4","6","7","8"],correctAnswer:"7",explanation:"x 대신 3을 넣으면 2 × 3 + 1 = 7입니다."},review:{summary:"문자의 값이 주어지면 문자 자리에 그 수를 넣어서 계산해요.",example:"x = 2일 때 3x = 3 × 2 = 6",question:{id:"m1-linear-v2-review-02",grade:"middle1",unit:"linear-equation",conceptId:"substitution",type:"multiple-choice",question:"a = 4일 때, 3a - 2의 값은 무엇일까요?",choices:["8","10","12","14"],correctAnswer:"10",explanation:"a 대신 4를 넣으면 3 × 4 - 2 = 10입니다."}}},
    {id:"like-terms",title:"동류항",description:"같은 문자끼리 계산할 수 있는지 확인해요.",question:{id:"m1-linear-v2-pre-03",grade:"middle1",unit:"linear-equation",conceptId:"like-terms",type:"multiple-choice",question:"3x + 2x를 간단히 하면 무엇일까요?",choices:["5","5x","6x","x"],correctAnswer:"5x",explanation:"같은 문자 x를 가진 항끼리는 계수를 더할 수 있으므로 5x입니다."},review:{summary:"같은 문자를 가진 항끼리는 앞의 숫자를 더하거나 뺄 수 있어요.",example:"4x + 3x = 7x",question:{id:"m1-linear-v2-review-03",grade:"middle1",unit:"linear-equation",conceptId:"like-terms",type:"multiple-choice",question:"7x - 2x를 간단히 하면 무엇일까요?",choices:["5","5x","9x","x"],correctAnswer:"5x",explanation:"7x와 2x는 동류항이므로 7 - 2 = 5, 따라서 5x입니다."}}},
    {id:"equality",title:"등식",description:"등호의 양쪽이 같은 값을 나타낸다는 뜻을 확인해요.",question:{id:"m1-linear-v2-pre-04",grade:"middle1",unit:"linear-equation",conceptId:"equality",type:"multiple-choice",question:"다음 중 등식은 무엇일까요?",choices:["3 + 2","x + 4","3 + 2 = 5","7 - x"],correctAnswer:"3 + 2 = 5",explanation:"등식은 '='를 사용하여 양쪽의 값이 같음을 나타낸 식입니다."},review:{summary:"등식은 등호 '='의 왼쪽과 오른쪽 값이 같다는 뜻이에요.",example:"2 + 3 = 5",question:{id:"m1-linear-v2-review-04",grade:"middle1",unit:"linear-equation",conceptId:"equality",type:"multiple-choice",question:"다음 중 양쪽의 값이 같은 등식은 무엇일까요?",choices:["2 + 4 = 5","3 + 4 = 7","8 - 2 = 5","4 × 2 = 6"],correctAnswer:"3 + 4 = 7",explanation:"3 + 4와 7은 모두 같은 값이므로 올바른 등식입니다."}}}
  ],
  coreConcepts:[
    {id:"equation-solution",title:"방정식과 해",lesson:{summary:"문자가 들어 있는 등식 중에서 문자의 값에 따라 참 또는 거짓이 되는 식을 방정식이라고 해요.",keyPoint:"방정식을 참이 되게 하는 문자의 값을 '해'라고 합니다.",example:"x + 2 = 5에서 x = 3을 넣으면 3 + 2 = 5가 되므로 해는 3입니다."},checkQuestion:{id:"m1-linear-v2-core-01",grade:"middle1",unit:"linear-equation",conceptId:"equation-solution",type:"multiple-choice",question:"방정식 x + 4 = 9의 해는 무엇일까요?",choices:["3","4","5","13"],correctAnswer:"5",explanation:"x = 5를 넣으면 5 + 4 = 9가 되므로 해는 5입니다."}},
    {id:"equality-properties",title:"등식의 성질",lesson:{summary:"등식의 양쪽에 같은 수를 더하거나 빼도 등식은 그대로 성립해요.",keyPoint:"등호의 양쪽에 반드시 같은 계산을 해야 균형이 유지됩니다.",example:"x + 3 = 7의 양쪽에서 3을 빼면 x = 4입니다."},checkQuestion:{id:"m1-linear-v2-core-02",grade:"middle1",unit:"linear-equation",conceptId:"equality-properties",type:"multiple-choice",question:"x + 6 = 10에서 x만 남기려면 양쪽에 어떤 계산을 해야 할까요?",choices:["6을 더한다","6을 뺀다","10을 더한다","10을 뺀다"],correctAnswer:"6을 뺀다",explanation:"x만 남기기 위해 등식의 양쪽에서 6을 빼야 합니다."}},
    {id:"transposition",title:"이항",lesson:{summary:"항을 등호 반대편으로 옮길 때 부호가 바뀌는 것을 이항이라고 해요.",keyPoint:"이항은 실제로 등식의 양쪽에 같은 수를 더하거나 빼는 과정을 짧게 나타낸 것입니다.",example:"x + 3 = 8 → x = 8 - 3"},checkQuestion:{id:"m1-linear-v2-core-03",grade:"middle1",unit:"linear-equation",conceptId:"transposition",type:"multiple-choice",question:"x - 4 = 7을 이항하여 나타낸 식은 무엇일까요?",choices:["x = 7 - 4","x = 7 + 4","x = 4 - 7","x = -7 - 4"],correctAnswer:"x = 7 + 4",explanation:"-4를 오른쪽으로 이항하면 +4가 됩니다."}},
    {id:"solve-linear-equation",title:"일차방정식 풀이",lesson:{summary:"문자항과 숫자항을 정리한 뒤 x의 계수가 1이 되도록 계산해요.",keyPoint:"정리 → 이항 → 계산 → x의 계수를 1로 만드는 순서로 풀면 됩니다.",example:"2x + 3 = 9 → 2x = 6 → x = 3"},checkQuestion:{id:"m1-linear-v2-core-04",grade:"middle1",unit:"linear-equation",conceptId:"solve-linear-equation",type:"multiple-choice",question:"2x + 4 = 10의 해는 무엇일까요?",choices:["2","3","4","7"],correctAnswer:"3",explanation:"2x + 4 = 10 → 2x = 6 → x = 3입니다."}}
  ],
  finalQuestions:[
    {id:"m1-linear-v2-final-01",grade:"middle1",unit:"linear-equation",conceptId:"equation-solution",level:"concept",type:"multiple-choice",question:"방정식 x - 2 = 6의 해는 무엇일까요?",choices:["4","6","8","12"],correctAnswer:"8",explanation:"x = 8을 넣으면 8 - 2 = 6이 됩니다."},
    {id:"m1-linear-v2-final-02",grade:"middle1",unit:"linear-equation",conceptId:"equality-properties",level:"concept",type:"multiple-choice",question:"x + 5 = 12에서 x를 구하기 위해 양쪽에서 같은 수를 빼려고 합니다. 어떤 수를 빼야 할까요?",choices:["5","7","12","17"],correctAnswer:"5",explanation:"x만 남기기 위해 등식의 양쪽에서 5를 뺍니다."},
    {id:"m1-linear-v2-final-03",grade:"middle1",unit:"linear-equation",conceptId:"transposition",level:"basic",type:"multiple-choice",question:"x + 7 = 15를 이항하여 나타낸 식은 무엇일까요?",choices:["x = 15 + 7","x = 15 - 7","x = 7 - 15","x = -15 - 7"],correctAnswer:"x = 15 - 7",explanation:"+7을 오른쪽으로 이항하면 -7이 됩니다."},
    {id:"m1-linear-v2-final-04",grade:"middle1",unit:"linear-equation",conceptId:"solve-linear-equation",level:"basic",type:"multiple-choice",question:"3x - 2 = 10의 해는 무엇일까요?",choices:["2","3","4","6"],correctAnswer:"4",explanation:"3x - 2 = 10 → 3x = 12 → x = 4입니다."},
    {id:"m1-linear-v2-final-05",grade:"middle1",unit:"linear-equation",conceptId:"solve-linear-equation",level:"application",type:"multiple-choice",question:"어떤 수에 2를 곱하고 3을 더했더니 11이 되었습니다. 어떤 수일까요?",choices:["3","4","5","7"],correctAnswer:"4",explanation:"어떤 수를 x라 하면 2x + 3 = 11입니다. 2x = 8이므로 x = 4입니다."}
  ]
}}};
window.MATH_CONCEPT_CONTENT=window.MATH_CONTENT;
